version = 0.1

[default.deploy.parameters]
stack_name = "ServerlessOrderProcessing"
resolve_s3 = true
s3_prefix = "ServerlessOrderProcessing"
region = "ap-south-1"
profile = "cloudpractise"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
